# -*- coding: utf-8 -*-
"""projeto_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KH5X5-BB8AnmqlucreMNNdNxCNWqsu_C
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.title("Dashboard - ENEGEP")
# 
# # Dados exemplo
# df = pd.DataFrame({
#     "Ano": [2020, 2021, 2022, 2023, 2024],
#     "Publicações": [120, 150, 170, 200, 230]
# })
# 
# st.subheader("Evolução de Publicações")
# fig = px.line(df, x="Ano", y="Publicações", markers=True)
# st.plotly_chart(fig)
# 
# st.write("Dashboard demonstrativo rodando no Google Colab 🚀")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# st.set_page_config(page_title="Dashboard ENEGEP", layout="wide")
# 
# st.title("📊 Dashboard Científico - ENEGEP")
# 
# st.markdown("Aplicação demonstrativa para apresentação em congresso.")
# 
# # =============================
# # Upload de dados
# # =============================
# st.sidebar.header("📂 Upload de Dados")
# uploaded_file = st.sidebar.file_uploader("Envie um arquivo CSV", type=["csv"])
# 
# if uploaded_file:
#     df = pd.read_csv(uploaded_file)
# else:
#     # Dados exemplo
#     df = pd.DataFrame({
#         "Ano": [2020, 2021, 2022, 2023, 2024],
#         "Publicações": [120, 150, 170, 200, 230],
#         "Área": ["Produção", "Produção", "Qualidade", "Qualidade", "Logística"]
#     })
# 
# # =============================
# # Filtros
# # =============================
# st.sidebar.header("🔎 Filtros")
# 
# if "Ano" in df.columns:
#     anos = st.sidebar.multiselect("Selecione o Ano", df["Ano"].unique(), default=df["Ano"].unique())
#     df = df[df["Ano"].isin(anos)]
# 
# if "Área" in df.columns:
#     areas = st.sidebar.multiselect("Selecione a Área", df["Área"].unique(), default=df["Área"].unique())
#     df = df[df["Área"].isin(areas)]
# 
# # =============================
# # Métricas
# # =============================
# col1, col2 = st.columns(2)
# 
# if "Publicações" in df.columns:
#     total = df["Publicações"].sum()
#     media = df["Publicações"].mean()
# 
#     col1.metric("Total de Publicações", int(total))
#     col2.metric("Média Anual", round(media, 2))
# 
# # =============================
# # Gráfico
# # =============================
# st.subheader("📈 Evolução das Publicações")
# 
# if "Ano" in df.columns and "Publicações" in df.columns:
#     fig = px.line(df, x="Ano", y="Publicações", color="Área" if "Área" in df.columns else None, markers=True)
#     st.plotly_chart(fig, use_container_width=True)
# 
# st.subheader("📋 Dados")
# st.dataframe(df)